# Generated by Django 4.2.11 on 2024-06-11 12:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_profile_about_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='images/nobody.jpg', max_length=255, verbose_name='image'),
        ),
    ]
